/**
 * Nokma / MeghFarm product catalogue.
 * Every figure, size and flavour here is taken from the company brochure
 * and the product pamphlet — nothing is invented.
 */

export const BRAND = {
  name: 'MeghFarm',
  flagship: 'Nokma',
  tagline: 'Fresh From Meghalaya',
  promise: ['Rooted in Meghalaya', 'Crafted for the World'],
  parent: 'Muktidata Multipurpose Co-operative Society Ltd.',
  established: 2017,
  registration: 'NO. T-3 OF 2017-18',
  registeredOn: '30th June 2017',
  registeredUnder:
    'The Meghalaya Co-operative Societies Act, 1971 (vide adoption of Laws Order NO. I of 1971)',
  address: {
    unit: 'MeghFarm Processing Hub',
    sub: '(A Unit of Muktidata Multipurpose Co-Operative Society Ltd.)',
    lines: ['Khamari, P.O. Hollaidanga', 'Dist — West Garo Hills', 'Meghalaya — 794109'],
  },
  phone: '+91 93663 23755',
  email: 'sales@themeghfarm.com',
  care: 'customercare@themeghfarm.com',
  website: 'www.themeghfarm.com',
  social: {
    instagram: '@nokma_meghfarm',
    facebook: '@meghfarm',
  },
  fssai: '11725006000073',
};

/* ------------------------------------------------------------------ *
 *  Ice cream flavours — the showcase carousel
 * ------------------------------------------------------------------ */
export const FLAVOURS = [
  {
    id: 'vanilla',
    name: 'Vanilla',
    sub: 'Tantalise White Temptation',
    img: 'flavour-vanilla',
    note: 'Snow-soft, slow-churned, the quiet classic every scoop is measured against.',
    formats: ['IML Container 100 / 125 ML', 'Round & Oval Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'Mono Carton 750 / 1000 ML'],
    theme: { bg: '#F6EEDC', deep: '#5A4526', ink: '#3A2C15', accent: '#C89A4A', glow: '#FFF3D6' },
  },
  {
    id: 'chocolate',
    name: 'Chocolate',
    sub: 'Deep Cocoa Indulgence',
    img: 'flavour-chocolate',
    note: 'Dark, rounded cocoa folded through rich Meghalaya cream.',
    formats: ['Round Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'IML Container 125 ML'],
    theme: { bg: '#EADCCF', deep: '#4A2C1B', ink: '#33200F', accent: '#8A5230', glow: '#F6E3D2' },
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    sub: 'Blush of the Hills',
    img: 'flavour-strawberry',
    note: 'Bright berry brought forward with real fruit pulp, never essence alone.',
    formats: ['Round Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'IML Container 125 ML'],
    theme: { bg: '#F7DDE6', deep: '#7A2745', ink: '#511628', accent: '#D4436F', glow: '#FFE7EF' },
  },
  {
    id: 'orange',
    name: 'Orange',
    sub: 'Sunrise Citrus',
    img: 'flavour-orange',
    note: 'A clean citrus lift — the first light over the Garo Hills, in a scoop.',
    formats: ['Round Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'IML Container 125 ML'],
    theme: { bg: '#FCE3CC', deep: '#8A3D0E', ink: '#5E2708', accent: '#E2731C', glow: '#FFEBD6' },
  },
  {
    id: 'jackfruit',
    name: 'Jackfruit',
    sub: 'Jack-A-licious',
    img: 'flavour-jackfruit',
    note: 'Meghalaya’s own jackfruit — honeyed, tropical, unmistakably regional.',
    formats: ['IML Container 100 / 125 ML', 'Round & Oval Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'Cone 45 / 80 / 110 ML'],
    theme: { bg: '#F8EBBE', deep: '#6E5410', ink: '#4A3806', accent: '#C9A21B', glow: '#FFF6D0' },
  },
  {
    id: 'butterscotch',
    name: 'Butterscotch',
    sub: 'Golden Crunch',
    img: 'flavour-butterscotch',
    note: 'Burnt-sugar warmth with a crunch that keeps finding you.',
    formats: ['IML Container 100 / 125 ML', 'Round & Oval Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'Cone 45 / 80 / 110 ML'],
    theme: { bg: '#F7E4C3', deep: '#6B4412', ink: '#472C06', accent: '#C4832A', glow: '#FFEFD5' },
  },
  {
    id: 'pistachio',
    name: 'Pistachio',
    sub: 'Tantalise Green Crush',
    img: 'flavour-pistachio',
    note: 'Nut-forward and gently savoury — the grown-up scoop of the range.',
    formats: ['IML Container 100 / 125 ML', 'Round & Oval Tub 750 / 1000 ML', 'Cup 55 / 70 ML'],
    theme: { bg: '#E7EDCE', deep: '#3F4F1C', ink: '#2A360F', accent: '#7B9435', glow: '#F3F8DC' },
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    sub: 'Field-Grown Sweetness',
    img: 'flavour-pineapple',
    note: 'From the same raw pineapples we supply in bulk — straight into cream.',
    formats: ['Round Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'IML Container 125 ML'],
    theme: { bg: '#E3EEDF', deep: '#1F4A32', ink: '#12301F', accent: '#3E8055', glow: '#EFF8EC' },
  },
  {
    id: 'lychee',
    name: 'Lychee',
    sub: 'Orchard Blush',
    img: 'flavour-lychee',
    note: 'Delicate, floral, faintly rose — the most fragile flavour we make.',
    formats: ['Round Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'IML Container 125 ML'],
    theme: { bg: '#FADCE3', deep: '#7B2438', ink: '#54141F', accent: '#CF4560', glow: '#FFE9EE' },
  },
  {
    id: 'ginger',
    name: 'Ginger',
    sub: 'Hill Spice',
    img: 'flavour-ginger',
    note: 'Made with our own dehydrated ginger — warm, clean, quietly bold.',
    formats: ['Round Tub 750 / 1000 ML', 'Cup 55 / 70 ML', 'IML Container 125 ML'],
    theme: { bg: '#F6E2CE', deep: '#7A3E14', ink: '#52270A', accent: '#C1701E', glow: '#FFEDDA' },
  },
  {
    id: 'lemon',
    name: 'Lemon',
    sub: 'Sharp & Clear',
    img: 'flavour-lemon',
    note: 'A cold, clean finish — the palate-cleanser of the collection.',
    formats: ['Cup 55 / 70 ML'],
    theme: { bg: '#EEF2D8', deep: '#4B5518', ink: '#333C0B', accent: '#8A9A2C', glow: '#F7FAE6' },
  },
  {
    id: 'banana',
    name: 'Banana',
    sub: 'Local Harvest',
    img: 'flavour-banana',
    note: 'The same local bananas that become our chips — churned soft and sweet.',
    formats: ['Cup 55 / 70 ML'],
    theme: { bg: '#F7EFC8', deep: '#655412', ink: '#443806', accent: '#B79C1E', glow: '#FFFAD8' },
  },
];

/* ------------------------------------------------------------------ *
 *  Product universe — every format, floating in 3D
 * ------------------------------------------------------------------ */
export const UNIVERSE = [
  {
    id: 'family-tub',
    img: 'family-tubs/jackfruit.png',
    name: 'Jackfruit Family Tub',
    kicker: 'Family Tub · Jackfruit',
    sizes: '750 ML · 1000 ML',
    blurb: 'Generous servings of happiness, made for parties, celebrations and joyful moments.',
    flavours: 'Jackfruit',
    cat: 'ice-cream',
  },
  {
    id: 'family-tub-vanilla',
    img: 'family-tubs/Vanilla.png',
    name: 'Vanilla Family Tub',
    kicker: 'Family Tub · Vanilla',
    sizes: '750 ML · 1000 ML',
    blurb: 'A generous vanilla ice cream tub made for sharing.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'family-tub-pistachio',
    img: 'family-tubs/pistachio.png',
    name: 'Pistachio Family Tub',
    kicker: 'Family Tub · Pistachio',
    sizes: '750 ML · 1000 ML',
    blurb: 'A rich pistachio ice cream tub made for sharing.',
    flavours: 'Pistachio',
    cat: 'ice-cream',
  },
  {
    id: 'family-tub-butterscotch',
    img: 'family-tubs/Butterscotch.png',
    name: 'Butterscotch Family Tub',
    kicker: 'Family Tub · Butterscotch',
    sizes: '750 ML · 1000 ML',
    blurb: 'A golden butterscotch ice cream tub made for sharing.',
    flavours: 'Butterscotch',
    cat: 'ice-cream',
  },
  {
    id: 'iml-vanilla',
    img: 'Ice Cream_Vanilla.png',
    name: 'Vanilla IML Container',
    kicker: 'IML Container · Vanilla',
    sizes: '100 ML · 125 ML',
    blurb: 'A smooth vanilla IML ice cream for an easy single serve.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'iml-chocolate',
    img: 'Ice Cream_Chocolate.png',
    name: 'Chocolate IML Container',
    kicker: 'IML Container · Chocolate',
    sizes: '100 ML · 125 ML',
    blurb: 'A rich chocolate IML ice cream for an easy single serve.',
    flavours: 'Chocolate',
    cat: 'ice-cream',
  },
  {
    id: 'iml-strawberry',
    img: 'strawberry png.png',
    name: 'Strawberry IML Container',
    kicker: 'IML Container · Strawberry',
    sizes: '100 ML · 125 ML',
    blurb: 'A bright strawberry IML ice cream for an easy single serve.',
    flavours: 'Strawberry',
    cat: 'ice-cream',
  },
  {
    id: 'iml-orange',
    img: 'Ice Cream_Orange.png',
    name: 'Orange IML Container',
    kicker: 'IML Container · Orange',
    sizes: '100 ML · 125 ML',
    blurb: 'A bright orange IML ice cream for an easy single serve.',
    flavours: 'Orange',
    cat: 'ice-cream',
  },
  {
    id: 'iml-jackfruit',
    img: 'Ice Cream_Jackfruit.png',
    name: 'Jackfruit IML Container',
    kicker: 'IML Container · Jackfruit',
    sizes: '100 ML · 125 ML',
    blurb: 'A tropical jackfruit IML ice cream for an easy single serve.',
    flavours: 'Jackfruit',
    cat: 'ice-cream',
  },
  {
    id: 'iml-butterscotch',
    img: 'Ice Cream_ButterScotch.png',
    name: 'Butterscotch IML Container',
    kicker: 'IML Container · Butterscotch',
    sizes: '100 ML · 125 ML',
    blurb: 'A golden butterscotch IML ice cream for an easy single serve.',
    flavours: 'Butterscotch',
    cat: 'ice-cream',
  },
  {
    id: 'iml-pistachio',
    img: 'Ice Cream_Pista.png',
    name: 'Pistachio IML Container',
    kicker: 'IML Container · Pistachio',
    sizes: '100 ML · 125 ML',
    blurb: 'A rich pistachio IML ice cream for an easy single serve.',
    flavours: 'Pistachio',
    cat: 'ice-cream',
  },
  {
    id: 'iml-pineapple',
    img: 'Ice Cream_Pineapple.png',
    name: 'Pineapple IML Container',
    kicker: 'IML Container · Pineapple',
    sizes: '100 ML · 125 ML',
    blurb: 'A fruit-forward pineapple IML ice cream for an easy single serve.',
    flavours: 'Pineapple',
    cat: 'ice-cream',
  },
  {
    id: 'iml-lychee',
    img: 'Ice Cream_Lychee.png',
    name: 'Lychee IML Container',
    kicker: 'IML Container · Lychee',
    sizes: '100 ML · 125 ML',
    blurb: 'A delicate lychee IML ice cream for an easy single serve.',
    flavours: 'Lychee',
    cat: 'ice-cream',
  },
  {
    id: 'iml-ginger',
    img: 'Ice Cream_Ginger.png',
    name: 'Ginger IML Container',
    kicker: 'IML Container · Ginger',
    sizes: '100 ML · 125 ML',
    blurb: 'A gently spiced ginger IML ice cream for an easy single serve.',
    flavours: 'Ginger',
    cat: 'ice-cream',
  },
  {
    id: 'cup-vanilla',
    img: 'cups-revised/cup (6).png',
    name: 'Vanilla Cup',
    kicker: 'Single Serve · Vanilla',
    sizes: '70 ML',
    blurb: 'A smooth vanilla ice cream made for an easy single serve.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'cup-jackfruit',
    img: 'cups-revised/cup (4).png',
    name: 'Jackfruit Cup',
    kicker: 'Single Serve · Jackfruit',
    sizes: '70 ML',
    blurb: 'A tropical jackfruit ice cream made for an easy single serve.',
    flavours: 'Jackfruit',
    cat: 'ice-cream',
  },
  {
    id: 'cup-ginger',
    img: 'cups-revised/cup (5).png',
    name: 'Ginger Cup',
    kicker: 'Single Serve · Ginger',
    sizes: '70 ML',
    blurb: 'A gently spiced ginger ice cream made for an easy single serve.',
    flavours: 'Ginger',
    cat: 'ice-cream',
  },
  {
    id: 'cup-orange',
    img: 'cups-revised/cup (3).png',
    name: 'Orange Cup',
    kicker: 'Single Serve · Orange',
    sizes: '70 ML',
    blurb: 'A bright orange ice cream made for an easy single serve.',
    flavours: 'Orange',
    cat: 'ice-cream',
  },
  {
    id: 'cup-lychee',
    img: 'cups-revised/cup (2).png',
    name: 'Lychee Cup',
    kicker: 'Single Serve · Lychee',
    sizes: '70 ML',
    blurb: 'A delicate lychee ice cream made for an easy single serve.',
    flavours: 'Lychee',
    cat: 'ice-cream',
  },
  {
    id: 'cup-lemon',
    img: 'cups-revised/cup (1).png',
    name: 'Lemon Cup',
    kicker: 'Single Serve · Lemon',
    sizes: '70 ML',
    blurb: 'A clean lemon ice cream made for an easy single serve.',
    flavours: 'Lemon',
    cat: 'ice-cream',
  },
  {
    id: 'cup-strawberry',
    img: 'cups-revised/cup.png',
    name: 'Strawberry Cup',
    kicker: 'Single Serve · Strawberry',
    sizes: '70 ML',
    blurb: 'A bright strawberry ice cream made for an easy single serve.',
    flavours: 'Strawberry',
    cat: 'ice-cream',
  },
  {
    id: 'cup-butterscotch',
    img: 'cups-revised/Untitled design (1).png',
    name: 'Butterscotch Cup',
    kicker: 'Single Serve · Butterscotch',
    sizes: '70 ML',
    blurb: 'A rich butterscotch ice cream made for an easy single serve.',
    flavours: 'Butterscotch',
    cat: 'ice-cream',
  },
  {
    id: 'cup-pineapple',
    img: 'cups-revised/Untitled design.png',
    name: 'Pineapple Cup',
    kicker: 'Single Serve · Pineapple',
    sizes: '70 ML',
    blurb: 'A fruit-forward pineapple ice cream made for an easy single serve.',
    flavours: 'Pineapple',
    cat: 'ice-cream',
  },
  {
    id: 'cone-royal-jack',
    img: 'cones/Royal Jack.png',
    name: 'Royal Jack Cone',
    kicker: 'Cone · Jackfruit',
    sizes: '45 ML · 80 ML · 110 ML',
    blurb: 'A jackfruit ice cream cone made for a crisp, creamy bite.',
    flavours: 'Jackfruit',
    cat: 'ice-cream',
  },
  {
    id: 'cone-butterscotch-80',
    img: 'cones/ButterScotch 80 ml.png',
    name: 'Butterscotch Cone',
    kicker: 'Cone · Butterscotch',
    sizes: '80 ML',
    blurb: 'A golden butterscotch ice cream cone with a crisp finish.',
    flavours: 'Butterscotch',
    cat: 'ice-cream',
  },
  {
    id: 'cone-vanilla-110',
    img: 'cones/Vanilla 110 ml.png',
    name: 'Vanilla Cone',
    kicker: 'Cone · Vanilla',
    sizes: '110 ML',
    blurb: 'A smooth vanilla ice cream cone with a crisp finish.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'cone-strawberry-45',
    img: 'cones/Strawberry 45.png',
    name: 'Strawberry Cone',
    kicker: 'Cone · Strawberry',
    sizes: '45 ML',
    blurb: 'A bright strawberry ice cream cone with a crisp finish.',
    flavours: 'Strawberry',
    cat: 'ice-cream',
  },
  {
    id: 'cone-chocolate-80',
    img: 'cones/80 ml choco.png',
    name: 'Chocolate Cone',
    kicker: 'Cone · Chocolate',
    sizes: '80 ML',
    blurb: 'A rich chocolate ice cream cone with a crisp finish.',
    flavours: 'Chocolate',
    cat: 'ice-cream',
  },
  {
    id: 'cone-vanilla-80',
    img: 'cones/Vanilla 80 ml.png',
    name: 'Vanilla Cone',
    kicker: 'Cone · Vanilla',
    sizes: '80 ML',
    blurb: 'A smooth vanilla ice cream cone with a crisp finish.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'cone-strawberry-80',
    img: 'cones/Strawberry 2.png',
    name: 'Strawberry Cone',
    kicker: 'Cone · Strawberry',
    sizes: '80 ML',
    blurb: 'A bright strawberry ice cream cone with a crisp finish.',
    flavours: 'Strawberry',
    cat: 'ice-cream',
  },
  {
    id: 'cone-butterscotch-110',
    img: 'cones/ButterScotch 110 ml.png',
    name: 'Butterscotch Cone',
    kicker: 'Cone · Butterscotch',
    sizes: '110 ML',
    blurb: 'A golden butterscotch ice cream cone with a crisp finish.',
    flavours: 'Butterscotch',
    cat: 'ice-cream',
  },
  {
    id: 'cone-vanilla-45',
    img: 'cones/Vanilla45 ml.png',
    name: 'Vanilla Cone',
    kicker: 'Cone · Vanilla',
    sizes: '45 ML',
    blurb: 'A smooth vanilla ice cream cone with a crisp finish.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'cone-jackfruit-110',
    img: 'cones/Jack 110.png',
    name: 'Jackfruit Cone',
    kicker: 'Cone · Jackfruit',
    sizes: '110 ML',
    blurb: 'A tropical jackfruit ice cream cone with a crisp finish.',
    flavours: 'Jackfruit',
    cat: 'ice-cream',
  },
  {
    id: 'carton-vanilla',
    img: 'carton-vanilla',
    name: 'Snow Drift Vanilla',
    kicker: 'Mono Carton',
    sizes: '750 ML · 1000 ML',
    blurb: 'Premium presentation paired with irresistible taste.',
    flavours: 'Vanilla',
    cat: 'ice-cream',
  },
  {
    id: 'carton-butterscotch',
    img: 'carton-butterscotch',
    name: 'Golden Crunch',
    kicker: 'Mono Carton',
    sizes: '750 ML · 1000 ML',
    blurb: 'Butterscotch, boxed for the table rather than the freezer aisle.',
    flavours: 'Butterscotch',
    cat: 'ice-cream',
  },
  {
    id: 'carton-jackfruit',
    img: 'carton-jackfruit',
    name: 'Jack-A-licious',
    kicker: 'Mono Carton',
    sizes: '750 ML · 1000 ML',
    blurb: 'Made with our own farm-fresh jackfruit.',
    flavours: 'Jackfruit',
    cat: 'ice-cream',
  },
  {
    id: 'drink-passion',
    img: 'drink-passion',
    name: 'Passion Fruit Drink',
    kicker: 'Nokma Beverages',
    sizes: '125 · 250 · 500 ML',
    blurb: 'Made from real fruit extracts, naturally refreshing.',
    flavours: 'Passion Fruit',
    cat: 'drinks',
  },
  {
    id: 'drink-pineapple',
    img: 'drink-pineapple',
    name: 'Pineapple Drink',
    kicker: 'Nokma Beverages',
    sizes: '125 · 320 · 500 ML',
    blurb: 'Meghalaya-grown pineapple, pressed and bottled.',
    flavours: 'Pineapple',
    cat: 'drinks',
  },
  {
    id: 'drink-lychee',
    img: 'drink-lychee',
    name: 'Lychee Drink',
    kicker: 'Nokma Beverages',
    sizes: '125 · 250 · 500 ML',
    blurb: 'Floral, light and cold — freshness in every sip.',
    flavours: 'Lychee',
    cat: 'drinks',
  },
  {
    id: 'water-bottle',
    img: 'water-bottle',
    name: 'Packaged Drinking Water',
    kicker: 'Blink · Shots · Squad',
    sizes: '250 ML · 500 ML · 1 L',
    blurb: 'Clean, refreshing water for every lifestyle — no compromise on purity.',
    flavours: 'Nokma BLINK 250 ML · SHOTS 500 ML · SQUAD 1 L',
    cat: 'drinks',
  },
  {
    id: 'chips-crispy',
    img: 'chips-crispy',
    name: 'Crispy Banana Chips',
    kicker: 'TE·RIK',
    sizes: '30 · 60 · 85 · 105 G',
    blurb: 'Crispy chips prepared from carefully selected local bananas.',
    flavours: 'Crispy',
    cat: 'chips',
  },
  {
    id: 'chips-plain',
    img: 'chips-plain',
    name: 'Plain Banana Chips',
    kicker: 'TE·RIK',
    sizes: '30 · 60 · 85 · 105 G',
    blurb: 'Light, crunchy and naturally delicious — hygienically packed for freshness.',
    flavours: 'Plain',
    cat: 'chips',
  },
  {
    id: 'spice-turmeric',
    img: 'spice-turmeric',
    name: 'Turmeric Powder',
    kicker: 'Dehydrated',
    sizes: '100 G · 500 G',
    blurb: 'Carefully processed to preserve aroma, colour and nutrition.',
    flavours: 'Chemical-free processing',
    cat: 'spices',
  },
  {
    id: 'spice-ginger',
    img: 'spice-ginger',
    name: 'Ginger Powder',
    kicker: 'Dehydrated',
    sizes: '100 G · 500 G',
    blurb: 'Pure flavour, traditional strength — naturally sourced.',
    flavours: 'Chemical-free processing',
    cat: 'spices',
  },
  {
    id: 'spice-green-chilli',
    img: 'spice-green-chilli.png',
    name: 'Green Chilli Powder',
    kicker: 'Dehydrated',
    sizes: '500 G',
    blurb: 'Dehydrated green chilli powder with a fresh, lively heat.',
    flavours: 'No added colours · No added preservatives',
    cat: 'spices',
  },
];

/* ------------------------------------------------------------------ *
 *  Ingredient pipeline
 * ------------------------------------------------------------------ */
export const INGREDIENTS = [
  { id: 'selection', label: 'Raw Material Selection', img: 'raw-pineapple', note: 'Selecting quality ingredients for every batch.' },
  { id: 'mix', label: 'Mix Preparation', img: 'story-processing', note: 'Preparing the ice cream mix to the required recipe.' },
  { id: 'pasteurization', label: 'Pasteurization & Homogenization', img: 'story-qc', note: 'Heat treatment and texture refinement for a smooth mix.' },
  { id: 'ageing', label: 'Ageing', img: 'iml-round', note: 'Resting the mix to develop body and a richer texture.' },
  { id: 'freezing', label: 'Freezing & Packaging', img: 'lineup', note: 'Freezing the mix and packing each product for sale.' },
  { id: 'distribution', label: 'Hardening & Distribution', img: 'story-delivery', note: 'Hardening the finished product before cold-chain distribution.' },
];

/* ------------------------------------------------------------------ *
 *  Impact counters
 * ------------------------------------------------------------------ */
export const IMPACT = [
  { id: 'flavours', value: 12, suffix: '', label: 'Ice Cream Flavours', note: 'From Vanilla to Jackfruit' },
  { id: 'lines', value: 5, suffix: '', label: 'Product Categories', note: 'Ice cream, drinks, water, chips and spices' },
  { id: 'formats', value: 30, suffix: '+', label: 'Pack Formats & Sizes', note: 'Cups, cones, tubs, cartons, bottles, pouches' },
  { id: 'since', value: 2024, suffix: '', label: 'Building Since', label2: 'Nokma production began in 2024', note: 'MeghFarm Processing Hub', raw: true },
];

export const IMPACT_PILLARS = [
  'Local sourcing',
  'Employment generation',
  'Women participation',
  'Sustainable livelihoods',
  'Regional brand development',
];
